openapi: 3.0.3
info:
  title: LifeChat API
  version: "1.0.0"
  description: API for logging and analyzing life events and feelings.
servers:
  - url: http://127.0.0.1:8000
paths:
  /addEvent:
    post:
      summary: Add a new event
      parameters:
        - name: description
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Event successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
  /addFeeling:
    post:
      summary: Add a new feeling
      parameters:
        - name: feelings
          in: query
          required: true
          schema:
            type: string
        - name: score
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Feeling successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feeling'
  /getAllEvents:
    get:
      summary: Retrieve all events
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  /getAllFeelings:
    get:
      summary: Retrieve all feelings
      responses:
        '200':
          description: List of feelings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feeling'
  /getEvents:
    get:
      summary: Get events between two datetimes.
      parameters:
        - name: startTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of events.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  /getFeelings:
    get:
      summary: Get feelings between two datetimes.
      parameters:
        - name: startTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of feelings.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feeling'

  /getAdvice:
    get:
      summary: Get advice based on a date range
      parameters:
        - name: startTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: AI-generated advice
          content:
            application/json:
              schema:
                type: string
  /lifeChat:
    post:
      summary: Submit a life chat and extract event/feeling
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chat:
                  type: string
      responses:
        '200':
          description: Extracted event and feeling
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    $ref: '#/components/schemas/Event'
                  feeling:
                    $ref: '#/components/schemas/Feeling'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        description:
          type: string
        tags:
          type: string
    Feeling:
      type: object
      properties:
        id:
          type: integer
        feelings:
          type: string
        score:
          type: integer
        datetime:
          type: string
          format: date-time
